import React from "react";
import { Route, Routes, NavLink } from "react-router-dom";
import Dashboard from "./pages/Dashboard";
import Universe from "./pages/Universe";
import Ticker from "./pages/Ticker";
import Watchlist from "./pages/Watchlist";

function Nav() {
  const link = (to: string, label: string) => (
    <NavLink
      to={to}
      className={({ isActive }) =>
        `px-3 py-2 rounded-xl text-sm transition ${isActive ? "bg-zinc-800" : "hover:bg-zinc-900"}`
      }
    >
      {label}
    </NavLink>
  );

  return (
    <div className="sticky top-0 z-10 backdrop-blur bg-zinc-950/70 border-b border-zinc-900">
      <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-2xl bg-gradient-to-br from-zinc-200 to-zinc-600" />
          <div>
            <div className="font-semibold leading-tight">Markets Analysis</div>
            <div className="text-xs text-zinc-400 -mt-0.5">Pages-first • deterministic benchmarking • cited sentiment</div>
          </div>
        </div>
        <div className="flex gap-2">
          {link("/", "Dashboard")}
          {link("/watchlist", "Watchlist")}
        </div>
      </div>
    </div>
  );
}

export default function App() {
  return (
    <div className="min-h-screen">
      <Nav />
      <div className="max-w-6xl mx-auto px-4 py-6">
        <Routes>
          <Route path="/" element={<Dashboard />} />
          <Route path="/watchlist" element={<Watchlist />} />
          <Route path="/u/:universeId" element={<Universe />} />
          <Route path="/t/:ticker" element={<Ticker />} />
        </Routes>
      </div>
      <footer className="border-t border-zinc-900 mt-10">
        <div className="max-w-6xl mx-auto px-4 py-6 text-xs text-zinc-500 flex justify-between">
          <div>Data generated by GitHub Actions.</div>
          <div>Not investment advice.</div>
        </div>
      </footer>
    </div>
  );
}
